//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18444
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlipEm.Res {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlipEm.Res.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 8
        ///0 0
        ///0 2
        ///0 3
        ///1 0
        ///2 3
        ///3 0
        ///3 1
        ///3 3.
        /// </summary>
        public static string Border_4 {
            get {
                return ResourceManager.GetString("Border_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 58
        ///1 0
        ///1 1
        ///1 2
        ///1 3
        ///1 4
        ///1 5
        ///1 6
        ///1 7
        ///1 8
        ///1 9
        ///2 1
        ///2 2
        ///2 3
        ///2 4
        ///2 5
        ///2 6
        ///2 7
        ///2 8
        ///3 0
        ///3 1
        ///3 8
        ///3 9
        ///4 1
        ///4 2
        ///4 7
        ///4 8
        ///5 0
        ///5 1
        ///5 4
        ///5 5
        ///5 8
        ///5 9
        ///6 1
        ///6 2
        ///6 7
        ///6 8
        ///7 0
        ///7 1
        ///7 8
        ///7 9
        ///8 1
        ///8 2
        ///8 3
        ///8 4
        ///8 5
        ///8 6
        ///8 7
        ///8 8
        ///9 0
        ///9 1
        ///9 2
        ///9 3
        ///9 4
        ///9 5
        ///9 6
        ///9 7
        ///9 8
        ///9 9
        ///.
        /// </summary>
        public static string BorderCross_10 {
            get {
                return ResourceManager.GetString("BorderCross_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 82
        ///1 0
        ///1 1
        ///1 2
        ///1 3
        ///1 4
        ///1 5
        ///1 6
        ///1 7
        ///1 8
        ///1 9
        ///1 10
        ///1 11
        ///2 1
        ///2 2
        ///2 3
        ///2 4
        ///2 5
        ///2 6
        ///2 7
        ///2 8
        ///2 9
        ///2 10
        ///3 0
        ///3 1
        ///3 10
        ///3 11
        ///4 1
        ///4 2
        ///4 9
        ///4 10
        ///5 0
        ///5 1
        ///5 4
        ///5 5
        ///5 6
        ///5 7
        ///5 10
        ///5 11
        ///6 1
        ///6 2
        ///6 5
        ///6 6
        ///6 9
        ///6 10
        ///7 0
        ///7 1
        ///7 4
        ///7 5
        ///7 6
        ///7 7
        ///7 10
        ///7 11
        ///8 1
        ///8 2
        ///8 9
        ///8 10
        ///9 0
        ///9 1
        ///9 10
        ///9 11
        ///10 1
        ///10 2
        ///10 3
        ///10 4
        ///10 5
        ///10 6
        ///10 7
        ///10 8
        ///10 9
        ///10 10
        ///11 0
        ///11 1
        ///11 2
        ///11 3
        ///11 4
        ///11 5
        ///11 6
        ///11 7
        ///11 8
        ///11 9
        ///11 10
        ///11 11
        ///.
        /// </summary>
        public static string BorderCross_12 {
            get {
                return ResourceManager.GetString("BorderCross_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 5
        ///0 1
        ///1 0
        ///1 1
        ///1 2
        ///2 1
        ///.
        /// </summary>
        public static string BorderCross_3 {
            get {
                return ResourceManager.GetString("BorderCross_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 6
        ///0 0
        ///0 1
        ///1 3
        ///2 3
        ///3 0
        ///3 1
        ///.
        /// </summary>
        public static string BorderCross_4 {
            get {
                return ResourceManager.GetString("BorderCross_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 22
        ///0 0
        ///1 0
        ///1 2
        ///1 3
        ///1 4
        ///1 5
        ///2 1
        ///2 3
        ///2 4
        ///3 0
        ///3 1
        ///3 3
        ///3 4
        ///3 5
        ///4 1
        ///4 2
        ///4 3
        ///5 0
        ///5 1
        ///5 2
        ///5 3
        ///5 4
        ///.
        /// </summary>
        public static string BorderCross_6 {
            get {
                return ResourceManager.GetString("BorderCross_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 40
        ///1 0
        ///1 1
        ///1 2
        ///1 3
        ///1 4
        ///1 5
        ///1 6
        ///1 7
        ///2 1
        ///2 2
        ///2 3
        ///2 4
        ///2 5
        ///2 6
        ///3 0
        ///3 1
        ///3 6
        ///3 7
        ///4 1
        ///4 2
        ///4 5
        ///4 6
        ///5 0
        ///5 1
        ///5 6
        ///5 7
        ///6 1
        ///6 2
        ///6 3
        ///6 4
        ///6 5
        ///6 6
        ///7 0
        ///7 1
        ///7 2
        ///7 3
        ///7 4
        ///7 5
        ///7 6
        ///7 7
        ///.
        /// </summary>
        public static string BorderCross_8 {
            get {
                return ResourceManager.GetString("BorderCross_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 36
        ///1 1
        ///1 2
        ///1 5
        ///1 6
        ///1 9
        ///1 10
        ///2 1
        ///2 2
        ///2 5
        ///2 6
        ///2 9
        ///2 10
        ///5 1
        ///5 2
        ///5 5
        ///5 6
        ///5 9
        ///5 10
        ///6 1
        ///6 2
        ///6 5
        ///6 6
        ///6 9
        ///6 10
        ///9 1
        ///9 2
        ///9 5
        ///9 6
        ///9 9
        ///9 10
        ///10 1
        ///10 2
        ///10 5
        ///10 6
        ///10 9
        ///10 10.
        /// </summary>
        public static string BorderDiagonalCross_11 {
            get {
                return ResourceManager.GetString("BorderDiagonalCross_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 36
        ///1 1
        ///1 2
        ///1 5
        ///1 6
        ///1 9
        ///1 10
        ///2 1
        ///2 2
        ///2 5
        ///2 6
        ///2 9
        ///2 10
        ///5 1
        ///5 2
        ///5 5
        ///5 6
        ///5 9
        ///5 10
        ///6 1
        ///6 2
        ///6 5
        ///6 6
        ///6 9
        ///6 10
        ///9 1
        ///9 2
        ///9 5
        ///9 6
        ///9 9
        ///9 10
        ///10 1
        ///10 2
        ///10 5
        ///10 6
        ///10 9
        ///10 10
        ///.
        /// </summary>
        public static string BorderDiagonalCross_12 {
            get {
                return ResourceManager.GetString("BorderDiagonalCross_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 4
        ///0 0
        ///1 0
        ///1 1
        ///2 1
        ///.
        /// </summary>
        public static string BorderDiagonalCross_3 {
            get {
                return ResourceManager.GetString("BorderDiagonalCross_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 4
        ///1 1
        ///1 2
        ///2 1
        ///2 2
        ///.
        /// </summary>
        public static string BorderDiagonalCross_4 {
            get {
                return ResourceManager.GetString("BorderDiagonalCross_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 16
        ///1 1
        ///1 2
        ///1 5
        ///1 6
        ///2 1
        ///2 2
        ///2 5
        ///2 6
        ///5 1
        ///5 2
        ///5 5
        ///5 6
        ///6 1
        ///6 2
        ///6 5
        ///6 6.
        /// </summary>
        public static string BorderDiagonalCross_7 {
            get {
                return ResourceManager.GetString("BorderDiagonalCross_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 16
        ///1 1
        ///1 2
        ///1 5
        ///1 6
        ///2 1
        ///2 2
        ///2 5
        ///2 6
        ///5 1
        ///5 2
        ///5 5
        ///5 6
        ///6 1
        ///6 2
        ///6 5
        ///6 6.
        /// </summary>
        public static string BorderDiagonalCross_8 {
            get {
                return ResourceManager.GetString("BorderDiagonalCross_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 44
        ///0 0
        ///0 2
        ///0 7
        ///0 9
        ///1 1
        ///1 4
        ///1 5
        ///1 8
        ///2 0
        ///2 2
        ///2 4
        ///2 5
        ///2 7
        ///2 9
        ///3 3
        ///3 6
        ///4 1
        ///4 2
        ///4 4
        ///4 5
        ///4 7
        ///4 8
        ///5 1
        ///5 2
        ///5 4
        ///5 5
        ///5 7
        ///5 8
        ///6 3
        ///6 6
        ///7 0
        ///7 2
        ///7 4
        ///7 5
        ///7 7
        ///7 9
        ///8 1
        ///8 4
        ///8 5
        ///8 8
        ///9 0
        ///9 2
        ///9 7
        ///9 9
        ///.
        /// </summary>
        public static string Cross_10 {
            get {
                return ResourceManager.GetString("Cross_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 63
        ///0 0
        ///0 4
        ///1 2
        ///1 6
        ///1 7
        ///1 8
        ///1 9
        ///1 10
        ///2 6
        ///2 10
        ///3 0
        ///3 1
        ///3 3
        ///3 4
        ///3 6
        ///3 7
        ///3 9
        ///3 10
        ///4 0
        ///4 1
        ///4 2
        ///4 3
        ///4 4
        ///4 5
        ///4 7
        ///4 8
        ///4 9
        ///5 1
        ///5 3
        ///5 4
        ///5 5
        ///5 10
        ///6 0
        ///6 1
        ///6 4
        ///6 9
        ///7 0
        ///7 3
        ///7 4
        ///7 5
        ///7 6
        ///7 7
        ///7 10
        ///8 0
        ///8 1
        ///8 3
        ///8 4
        ///8 7
        ///8 9
        ///9 1
        ///9 2
        ///9 5
        ///9 6
        ///9 7
        ///9 8
        ///9 10
        ///10 0
        ///10 2
        ///10 3
        ///10 4
        ///10 5
        ///10 7
        ///10 8
        ///.
        /// </summary>
        public static string Cross_11 {
            get {
                return ResourceManager.GetString("Cross_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 72
        ///0 0
        ///0 2
        ///0 9
        ///0 11
        ///1 1
        ///1 4
        ///1 5
        ///1 6
        ///1 7
        ///1 10
        ///2 0
        ///2 2
        ///2 4
        ///2 7
        ///2 9
        ///2 11
        ///3 3
        ///3 4
        ///3 5
        ///3 6
        ///3 7
        ///3 8
        ///4 1
        ///4 2
        ///4 3
        ///4 4
        ///4 7
        ///4 8
        ///4 9
        ///4 10
        ///5 1
        ///5 3
        ///5 5
        ///5 6
        ///5 8
        ///5 10
        ///6 1
        ///6 3
        ///6 5
        ///6 6
        ///6 8
        ///6 10
        ///7 1
        ///7 2
        ///7 3
        ///7 4
        ///7 7
        ///7 8
        ///7 9
        ///7 10
        ///8 3
        ///8 4
        ///8 5
        ///8 6
        ///8 7
        ///8 8
        ///9 0
        ///9 2
        ///9 4
        ///9 7
        ///9 9
        ///9 11
        ///10 1
        ///10 4
        ///10 5
        ///10 6
        ///10 7
        ///10 10
        ///11 0
        ///11 2
        ///11 9
        ///11 11
        ///.
        /// </summary>
        public static string Cross_12 {
            get {
                return ResourceManager.GetString("Cross_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 5
        ///0 0
        ///0 2
        ///1 1
        ///2 0
        ///2 2
        ///.
        /// </summary>
        public static string Cross_3 {
            get {
                return ResourceManager.GetString("Cross_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 4
        ///0 2
        ///1 0
        ///2 3
        ///3 1
        ///.
        /// </summary>
        public static string Cross_4 {
            get {
                return ResourceManager.GetString("Cross_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 15
        ///0 3
        ///0 4
        ///1 0
        ///1 1
        ///1 3
        ///1 4
        ///2 0
        ///2 1
        ///2 2
        ///3 1
        ///3 2
        ///3 3
        ///4 0
        ///4 2
        ///4 3
        ///.
        /// </summary>
        public static string Cross_5 {
            get {
                return ResourceManager.GetString("Cross_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 28
        ///0 0
        ///0 2
        ///0 3
        ///0 5
        ///1 1
        ///1 2
        ///1 3
        ///1 4
        ///2 0
        ///2 1
        ///2 2
        ///2 3
        ///2 4
        ///2 5
        ///3 0
        ///3 1
        ///3 2
        ///3 3
        ///3 4
        ///3 5
        ///4 1
        ///4 2
        ///4 3
        ///4 4
        ///5 0
        ///5 2
        ///5 3
        ///5 5
        ///.
        /// </summary>
        public static string Cross_6 {
            get {
                return ResourceManager.GetString("Cross_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 33
        ///0 0
        ///0 1
        ///0 3
        ///0 5
        ///0 6
        ///1 0
        ///1 1
        ///1 2
        ///1 4
        ///1 5
        ///1 6
        ///2 1
        ///2 2
        ///2 4
        ///2 5
        ///3 0
        ///3 3
        ///3 6
        ///4 1
        ///4 2
        ///4 4
        ///4 5
        ///5 0
        ///5 1
        ///5 2
        ///5 4
        ///5 5
        ///5 6
        ///6 0
        ///6 1
        ///6 3
        ///6 5
        ///6 6
        ///.
        /// </summary>
        public static string Cross_7 {
            get {
                return ResourceManager.GetString("Cross_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 40
        ///0 0
        ///0 1
        ///0 6
        ///0 7
        ///1 0
        ///1 1
        ///1 3
        ///1 4
        ///1 6
        ///1 7
        ///2 2
        ///2 3
        ///2 4
        ///2 5
        ///3 1
        ///3 2
        ///3 3
        ///3 4
        ///3 5
        ///3 6
        ///4 1
        ///4 2
        ///4 3
        ///4 4
        ///4 5
        ///4 6
        ///5 2
        ///5 3
        ///5 4
        ///5 5
        ///6 0
        ///6 1
        ///6 3
        ///6 4
        ///6 6
        ///6 7
        ///7 0
        ///7 1
        ///7 6
        ///7 7
        ///.
        /// </summary>
        public static string Cross_8 {
            get {
                return ResourceManager.GetString("Cross_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 41
        ///0 0
        ///0 2
        ///0 3
        ///0 4
        ///0 4
        ///0 7
        ///1 1
        ///1 2
        ///1 3
        ///1 5
        ///2 0
        ///2 1
        ///2 2
        ///2 4
        ///2 8
        ///3 0
        ///3 1
        ///3 5
        ///3 6
        ///4 2
        ///4 3
        ///4 4
        ///4 5
        ///4 6
        ///5 1
        ///5 2
        ///5 5
        ///5 8
        ///6 1
        ///6 3
        ///6 4
        ///6 5
        ///6 6
        ///7 1
        ///7 3
        ///7 5
        ///7 6
        ///8 1
        ///8 2
        ///8 3
        ///8 8
        ///.
        /// </summary>
        public static string Cross_9 {
            get {
                return ResourceManager.GetString("Cross_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 4
        ///0 0
        ///0 1
        ///1 1
        ///1 2
        ///.
        /// </summary>
        public static string DiagonalCross_3 {
            get {
                return ResourceManager.GetString("DiagonalCross_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 4
        ///1 1
        ///1 2
        ///2 1
        ///2 2
        ///.
        /// </summary>
        public static string DiagonalCross_4 {
            get {
                return ResourceManager.GetString("DiagonalCross_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 15
        ///0 3
        ///0 4
        ///1 0
        ///1 1
        ///1 3
        ///1 4
        ///2 0
        ///2 1
        ///2 2
        ///3 1
        ///3 2
        ///3 3
        ///4 0
        ///4 2
        ///4 3
        ///.
        /// </summary>
        public static string fcheck {
            get {
                return ResourceManager.GetString("fcheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 16
        ///0 0
        ///0 3
        ///0 6
        ///0 9
        ///3 0
        ///3 3
        ///3 6
        ///3 9
        ///6 0
        ///6 3
        ///6 6
        ///6 9
        ///9 0
        ///9 3
        ///9 6
        ///9 9
        ///.
        /// </summary>
        public static string Square_10 {
            get {
                return ResourceManager.GetString("Square_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 16
        ///1 1
        ///1 4
        ///1 7
        ///1 10
        ///4 0
        ///4 3
        ///4 6
        ///4 9
        ///7 0
        ///7 3
        ///7 6
        ///7 9
        ///10 0
        ///10 3
        ///10 6
        ///10 9
        ///.
        /// </summary>
        public static string Square_11 {
            get {
                return ResourceManager.GetString("Square_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 16
        ///1 1
        ///1 4
        ///1 7
        ///1 10
        ///4 1
        ///4 4
        ///4 7
        ///4 10
        ///7 1
        ///7 4
        ///7 7
        ///7 10
        ///10 1
        ///10 4
        ///10 7
        ///10 10
        ///.
        /// </summary>
        public static string Square_12 {
            get {
                return ResourceManager.GetString("Square_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1
        ///1 1
        ///.
        /// </summary>
        public static string Square_3 {
            get {
                return ResourceManager.GetString("Square_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 4
        ///0 0
        ///0 3
        ///3 0
        ///3 3
        ///.
        /// </summary>
        public static string Square_4 {
            get {
                return ResourceManager.GetString("Square_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 4
        ///0 0
        ///0 3
        ///3 0
        ///3 3
        ///.
        /// </summary>
        public static string Square_5 {
            get {
                return ResourceManager.GetString("Square_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 4
        ///1 1
        ///1 4
        ///4 1
        ///4 4
        ///.
        /// </summary>
        public static string Square_6 {
            get {
                return ResourceManager.GetString("Square_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 9
        ///0 0
        ///0 3
        ///0 6
        ///3 0
        ///3 3
        ///3 6
        ///6 0
        ///6 3
        ///6 6
        ///.
        /// </summary>
        public static string Square_7 {
            get {
                return ResourceManager.GetString("Square_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 9
        ///1 1
        ///1 4
        ///1 7
        ///4 1
        ///4 4
        ///4 7
        ///7 1
        ///7 4
        ///7 7
        ///.
        /// </summary>
        public static string Square_8 {
            get {
                return ResourceManager.GetString("Square_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 9
        ///1 1
        ///1 4
        ///1 7
        ///4 1
        ///4 4
        ///4 7
        ///7 1
        ///7 4
        ///7 7
        ///.
        /// </summary>
        public static string Square_9 {
            get {
                return ResourceManager.GetString("Square_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 0
        ///.
        /// </summary>
        public static string Steps_sequence {
            get {
                return ResourceManager.GetString("Steps_sequence", resourceCulture);
            }
        }
    }
}
